# Generated by Django 5.1.5 on 2025-02-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_type_user_create_at_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessaccount',
            old_name='reistration_number',
            new_name='registration_number',
        ),
    ]
