# Generated by Django 5.1.5 on 2025-03-07 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otp_totp.totpdevice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
