# Generated by Django 5.1.5 on 2025-03-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username_userotpdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwofactorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_twofa_enable', models.BooleanField(default=False)),
                ('twofacode', models.CharField(max_length=200)),
                ('twofactor_created', models.DateTimeField(blank=True, null=True)),
                ('twofa_back', models.JSONField(blank=True, default=list)),
                ('is_email_enable', models.BooleanField(default=False)),
                ('email_otp', models.CharField(blank=True, max_length=200, null=True)),
                ('email_created', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofactor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserOTPDevice',
        ),
    ]
