# Generated by Django 5.1.5 on 2025-03-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_twofactormodel_delete_userotpdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twofactormodel',
            old_name='is_email_enable',
            new_name='is_email_enabled',
        ),
        migrations.RenameField(
            model_name='twofactormodel',
            old_name='is_twofa_enable',
            new_name='is_twofa_enabled',
        ),
        migrations.RenameField(
            model_name='twofactormodel',
            old_name='twofa_back',
            new_name='twofa_backup',
        ),
    ]
